name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

  deploy:
    needs: frontend-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          script: |
            cd ~/devops-mean/Frontend
            git pull

            cd ~/devops-mean
            docker compose up -d --build frontend
